-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE skoshes (
    id SERIAL PRIMARY KEY,
    user_id bigint NOT NULL,
    skosh_type integer NOT NULL,
    caption text NOT NULL,
    image bytea NOT NULL,
    likes integer NOT NULL DEFAULT 0,
    "createdAt" bigint NOT NULL,
    "updatedAt" bigint NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX skoshes_pkey ON skoshes(id int4_ops);
